---

- name: Ansible Lightspeed with IBM watsonx Code Assistant
  hosts: localhost
  vars: 
    base_url: https://c.ai.ansible.redhat.com/
  tasks:

  # https://github.com/ansible/ansible-ai-connect-service/blob/main/tools/openapi-schema/ansible-ai-connect-service.yaml
  # https://github.com/ansible/ansible-ai-connect-service/blob/main/README.md
  - name: Get Playbook code
    ansible.builtin.uri:
      url: "{{ base_url }}"
      method: "POST"
      status_code:
        - 200
      #body_format: "{{ body_format }}"
      #return_content: true
      headers:
        "Content-Type: application/x-www-form-urlencoded"
      body: "grant_type=urn:ibm:params:oauth:grant-type:apikey&apikey={{ APIKEY }}"
    environment:
      SOCIAL_AUTH_OIDC_OIDC_ENDPOINT: "https://sso.redhat.com/auth/realms/redhat-external"
      SOCIAL_AUTH_OIDC_KEY: "ansible-wisdom-staging"
      SOCIAL_AUTH_OIDC_SECRET: secret_value
