---

- name: IBM watsonx Code Assistant - API test
  hosts: localhost
  vars: 
    iam_url: https://iam.cloud.ibm.com/identity/token
    base_url: https://eu-de.ml.cloud.ibm.com
  tasks:

    # curl -X POST 'https://iam.cloud.ibm.com/identity/token' -H 'Content-Type: application/x-www-form-urlencoded' -d 'grant_type=urn:ibm:params:oauth:grant-type:apikey&apikey=MY_APIKEY'
    # {
    # "access_token": "eyJhbGciOiJIUz......sgrKIi8hdFs",
    # "refresh_token": "SPrXw5tBE3......KBQ+luWQVY=",
    # "token_type": "Bearer",
    # "expires_in": 3600,
    # "expiration": 1473188353
    # }
  - name: Get Token
    ansible.builtin.uri:
      url: "{{ iam_url }}"
      method: "POST"
      #body_format: "{{ body_format }}"
      status_code: 200
      #return_content: true
      headers:
        "Content-Type: application/x-www-form-urlencoded"
      body: "grant_type=urn:ibm:params:oauth:grant-type:apikey&apikey={{ APIKEY }}"
    register: token

  - name: Debug Token
    debug:
      var: token
  
  - name: Get Playbook code
    ansible.builtin.uri:
      url: "{{ base_url }}"
      method: "POST"
      status_code:
        - 200
      #body_format: "{{ body_format }}"
      #return_content: true
      headers:
        "Content-Type: application/x-www-form-urlencoded"
      body: "grant_type=urn:ibm:params:oauth:grant-type:apikey&apikey={{ APIKEY }}"
