---

- name: Ansible Lightspeed with IBM watsonx Code Assistant
  hosts: localhost
  vars: 
    base_url: https://c.ai.ansible.redhat.com/
  tasks:

  # https://github.com/ansible/ansible-ai-connect-service/blob/main/tools/openapi-schema/ansible-ai-connect-service.yaml
  # https://github.com/ansible/ansible-ai-connect-service/blob/main/README.md
  - name: Authenticate RH SSO
    ansible.builtin.uri:
      url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
      method: POST
      return_content: yes
      status_code: 200
      validate_certs: no
      body_format: form-urlencoded
      body:
        grant_type: "refresh_token"
        client_id: "rhsm-api"
        refresh_token: "{{offline_token }}"
    register: token

  - name: Debug token
    debug:
      var: token

  - name: set fact token_content
    set_fact: 
      token_content: "{{ token.content | from_json }}"

  - name: set fact access_token
    set_fact: 
      access_token: "{{ token_content.access_token }}"

  - name: Debug access_token
    debug:
      msg: "{{ access_token }}"

  # https://github.com/ansible/ansible-ai-connect-service/blob/main/tools/openapi-schema/ansible-ai-connect-service.yaml
  # https://github.com/ansible/ansible-ai-connect-service/blob/main/README.md
  - name: Get AI Completions
    ansible.builtin.uri:
      url: "https://c.ai.ansible.redhat.com/api/v0/ai/completions/"
      method: POST
      return_content: yes
      status_code: 200
      validate_certs: no
      headers:
        Content-Type: "application/json"
        Accept: "application/json"
        Authorization: "Bearer {{ token }}"
      body_format: form-urlencoded
      body: '"prompt": "---\n- hosts: all\n  tasks:\n  - name: Install nginx and nodejs 12 Packages\n"}'
      # body:
      #   prompt: |
      #     ---
          
      #     - hosts: all
      #       tasks:
      #         - name: Install nginx and nodejs 12 Packages
    register: output

  - name: Debug output
    debug:
      var: output

  - name: Debug predictions
    debug:
      var: predictions
