---

- name: Ansible Lightspeed with IBM watsonx Code Assistant
  hosts: localhost
  vars: 
    base_url: https://c.ai.ansible.redhat.com/
  tasks:

  # https://github.com/ansible/ansible-ai-connect-service/blob/main/tools/openapi-schema/ansible-ai-connect-service.yaml
  # https://github.com/ansible/ansible-ai-connect-service/blob/main/README.md
  - name: Get Playbook code
    ansible.builtin.uri:
      url: "https://sso.redhat.com/auth/realms/redhat-external"
      method: POST
      body: "grant_type=pass&client_id=admin-cli&username=mgmtuser&password=mgmtpass"
      return_content: yes
      status_code: 200
      validate_certs: no
    register: login

  - name: Debug login
    debug:
      var: login