# - name: create vlans on cisco ios

#1
- name: create vlans on cisco ios
  ansible.builtin.gather_facts: false
  hosts: cisco
  tasks:
  - name: Create VLAN on cisco ios
    cisco.ios.ios_vlans:
      state: present
      config:
      - name: new_vlan
        vlan_id: 100
        state: present

#2
- name: create vlans on cisco ios
  ansible.builtin.cli_config:
    config: ip address {{ ansible_net_hostname }} vlan {{ ansible_net_hostname }} vlan {{
      ansible_net_hostname }}
    diff_mode: modified
  vars:
    ansible_connection: ansible.netcommon.network_cli

#3
- name: create vlans on cisco ios
  cisco.ios.ios_vlans:
    config:
      - name: vlan99
        vlan_id: 201
        state: overridden
    state: merged
  tags:
    - always
  register: _vlans_output







- name: set cisco ios ip address
  ansible.builtin.template:
    src: ios.j2
    dest: ip address{{ ansible_net_hostname }}
    diff_mode: modified
  vars:
    ansible_connection: ansible.netcommon.network_cli


  cisco.ios.ios_config:
    lines:
      - ip address {{ _os_router_address }}



######## EXPECTED ########

- name: create cisco ios vlans
  vars:
    vlans:
    - name: VLAN100
      vlan_id: 100
      state: active
  cisco.ios.ios_vlans:
    config: "{{ vlans }}"
    state: merged






