---

- name: AWS RHEL Deployment
  hosts: aws
  tasks:
    - name: create vpc with variables
      amazon.aws.ec2_vpc_net:
        name: "{{ _name_ }}"
        cidr_block: "{{ _cidr_block_ }}"
        region: "{{ _region_ }}"
        state: present
        aws_access_key: "{{ _aws_access_key_ }}"
        aws_secret_key: "{{ _aws_secret_key_ }}"
      register: vpc
    
    - name: create a subnet
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{ _vpc_id_ }}"
        region: "{{ _region_ }}"
        cidr: "{{ _cidr_ }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        tags:
          Name: "{{ _name }}"
      register: subnet
    
    - name: create an igw
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ _vpc_id_ }}"
        region: "{{ _region_ }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        state: present
        tags:
          Name: "{{ _name }}"
      register: igw
    
    - name: create route tables and igw route
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ _vpc_id_ }}"
        region: "{{ _region_ }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        subnets:
          - "{{ subnet.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
        tags:
          Name: "{{ _name }}"
      register: route_table
    
    - name: create sg and open port 80, 443 and 22
    

